version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://172.20.10.4:8080
      - REACT_APP_BACKEND_SERVICE_URL=http://172.20.10.3:8081
      - CHOKIDAR_USEPOLLING=true
    networks:
      - frontend-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  frontend-network:
    driver: bridge
    name: frontend-network
