version: '3.8'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - JWT_SECRET=your-secret-key-here-change-in-production
    networks:
      app-network:
        ipv4_address: 172.20.10.4
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend-service:
    build: ./backend-service
    container_name: backend-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - AUTH_SERVICE_URL=http://172.20.10.4:8080
    depends_on:
      - auth-service
    networks:
      app-network:
        ipv4_address: 172.20.10.3
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://172.20.10.4:8080
      - REACT_APP_BACKEND_SERVICE_URL=http://172.20.10.3:8081
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - auth-service
      - backend-service
    networks:
      app-network:
        ipv4_address: 172.20.10.2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.10.0/24
