version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    networks:
      - app-network

  backend-service:
    build: ./backend-service
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - AUTH_SERVICE_URL=http://172.20.10.4:8080
    depends_on:
      - auth-service
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH_SERVICE_URL=http://172.20.10.4:8080
      - REACT_APP_BACKEND_SERVICE_URL=http://172.20.10.3:8081
    depends_on:
      - auth-service
      - backend-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
