services:
  backend-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      - PORT=8081
      - AUTH_SERVICE_URL=http://172.20.10.4:8080
      - CORS_ADDITIONAL_ORIGINS=http://172.20.10.2:3000,http://172.20.10.2
    restart: unless-stopped
    network_mode: "host"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
